import = [
	# Catppuccin.
	"~/.config/alacritty/catppuccin-mocha.toml"
]

# Terminal env vars.
[env]
	TERM = "xterm-256color"

# Font.
[font]
	normal = { family = "Hack Nerd Font Mono" }
	size = 12

# Hpome comforts.
[keyboard]
bindings = [
	# Option key left and right skips word.
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

